// Generated by gencpp from file my_custom_msgs/LidarData.msg
// DO NOT EDIT!


#ifndef MY_CUSTOM_MSGS_MESSAGE_LIDARDATA_H
#define MY_CUSTOM_MSGS_MESSAGE_LIDARDATA_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace my_custom_msgs
{
template <class ContainerAllocator>
struct LidarData_
{
  typedef LidarData_<ContainerAllocator> Type;

  LidarData_()
    : header()
    , lidar_values()
    , additional_data()  {
      lidar_values.assign(0.0);
  }
  LidarData_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , lidar_values()
    , additional_data()  {
      lidar_values.assign(0.0);

      additional_data.assign(std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>(_alloc));
  }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef boost::array<float, 360>  _lidar_values_type;
  _lidar_values_type lidar_values;

   typedef boost::array<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>, 8>  _additional_data_type;
  _additional_data_type additional_data;





  typedef boost::shared_ptr< ::my_custom_msgs::LidarData_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::my_custom_msgs::LidarData_<ContainerAllocator> const> ConstPtr;

}; // struct LidarData_

typedef ::my_custom_msgs::LidarData_<std::allocator<void> > LidarData;

typedef boost::shared_ptr< ::my_custom_msgs::LidarData > LidarDataPtr;
typedef boost::shared_ptr< ::my_custom_msgs::LidarData const> LidarDataConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::my_custom_msgs::LidarData_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::my_custom_msgs::LidarData_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::my_custom_msgs::LidarData_<ContainerAllocator1> & lhs, const ::my_custom_msgs::LidarData_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.lidar_values == rhs.lidar_values &&
    lhs.additional_data == rhs.additional_data;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::my_custom_msgs::LidarData_<ContainerAllocator1> & lhs, const ::my_custom_msgs::LidarData_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace my_custom_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::my_custom_msgs::LidarData_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::my_custom_msgs::LidarData_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::my_custom_msgs::LidarData_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::my_custom_msgs::LidarData_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::my_custom_msgs::LidarData_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::my_custom_msgs::LidarData_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::my_custom_msgs::LidarData_<ContainerAllocator> >
{
  static const char* value()
  {
    return "fb0d95f66fac873e7d29547736862403";
  }

  static const char* value(const ::my_custom_msgs::LidarData_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xfb0d95f66fac873eULL;
  static const uint64_t static_value2 = 0x7d29547736862403ULL;
};

template<class ContainerAllocator>
struct DataType< ::my_custom_msgs::LidarData_<ContainerAllocator> >
{
  static const char* value()
  {
    return "my_custom_msgs/LidarData";
  }

  static const char* value(const ::my_custom_msgs::LidarData_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::my_custom_msgs::LidarData_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n"
"float32[360] lidar_values\n"
"string[8] additional_data\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
;
  }

  static const char* value(const ::my_custom_msgs::LidarData_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::my_custom_msgs::LidarData_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.lidar_values);
      stream.next(m.additional_data);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct LidarData_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::my_custom_msgs::LidarData_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::my_custom_msgs::LidarData_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "lidar_values[]" << std::endl;
    for (size_t i = 0; i < v.lidar_values.size(); ++i)
    {
      s << indent << "  lidar_values[" << i << "]: ";
      Printer<float>::stream(s, indent + "  ", v.lidar_values[i]);
    }
    s << indent << "additional_data[]" << std::endl;
    for (size_t i = 0; i < v.additional_data.size(); ++i)
    {
      s << indent << "  additional_data[" << i << "]: ";
      Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.additional_data[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // MY_CUSTOM_MSGS_MESSAGE_LIDARDATA_H
